import { Country } from "../interfaces/Country"

export const countries: Country[] = [
	{	code: "AF",	name: "Afeganistão", continents: ["Ásia"] },
	{	code: "ZA",	name: "África do Sul", continents: ["África"] },
	{	code: "AX",	name: "Aland, Ilhas",	continents: ["Europa"] },
	{	code: "AL",	name: "Albânia", continents: ["Europa"]	},
	{	code: "DE",	name: "Alemanha",	continents: ["Europa"] },
	{	code: "AD",	name: "Andorra", continents: ["Europa"] },
	{	code: "AO",	name: "Angola",	continents: ["África"] },
	{	code: "AI",	name: "Anguila", continents: ["América"] },
	{	code: "AQ",	name: "Antártida", continents: ["Indefinido"] },
	{	code: "AG",	name: "Antígua e Barbuda", continents: ["América"] },
	{	code: "SA",	name: "Arábia Saudita",	continents: ["Ásia"] },
	{	code: "DZ",	name: "Argélia", continents: ["África"] },
	{ code: "AR", name: "Argentina", continents: ["América"] },
	{	code: "AM",	name: "Armênia", continents: ["Ásia"] },
	{ code: "AW", name: "Aruba", continents: ["América"] },
	{ code: "AU", name: "Austrália", continents: ["Oceania"] },
	{ code: "AT", name: "Áustria", continents: ["Europa"] },
	{ code: "AZ", name: "Azerbaijão", continents: ["Ásia"] },
	{ code: "BS", name: "Bahamas", continents: ["América"] },
	{ code: "BD", name: "Bangladesh", continents: ["Ásia"] },
	{ code: "BB", name: "Barbados", continents: ["América"] },
	{ code: "BH", name: "Bahrain", continents: ["Ásia"] },
	{ code: "BE", name: "Bélgica", continents: ["Europa"] },
	{ code: "BZ", name: "Belize", continents: ["América"] },
	{ code: "BJ", name: "Benim", continents: ["África"] },
	{ code: "BM", name: "Bermudas", continents: ["América"] },
	{ code: "BY", name: "Bielorrússia", continents: ["Europa"] },
	{ code: "BO", name: "Bolívia", continents: ["América"] },
	{ code: "BQ", name: "Bonaire, Santo Eustáquio e Saba", continents: ["América"] },
	{ code: "BA", name: "Bósnia e Herzegovina", continents: ["Europa"] },
	{ code: "BW", name: "Botsuana", continents: ["África"] },
	{ code: "BV", name: "Ilha Bouvet", continents: ["Indefinido"] },
	{ code: "BR", name: "Brasil", continents: ["América"] },
	{ code: "BN", name: "Brunei", continents: ["Ásia"] },
	{ code: "BG", name: "Bulgária", continents: ["Europa"] },
	{ code: "BF", name: "Burquina Fasso", continents: ["África"] },
	{ code: "BI", name: "Burundi", continents: ["África"] },
	{ code: "BT", name: "Butão", continents: ["Ásia"] },
	{ code: "CV", name: "Cabo Verde", continents: ["África"] },
	{ code: "KY", name: "Ilhas Caimã", continents: ["América"] },
	{ code: "KH", name: "Camboja", continents: ["Ásia"] },
	{ code: "CM", name: "Camarões", continents: ["África"] },
	{ code: "CA", name: "Canadá", continents: ["América"] },
	{ code: "QA", name: "Catar", continents: ["Ásia"] },
	{ code: "KZ", name: "Cazaquistão", continents: ["Ásia"] },
	{ code: "CF", name: "República Centro-Africana", continents: ["África"] },
	{ code: "TD", name: "Chade", continents: ["África"] },
	{ code: "CZ", name: "Chéquia", continents: ["Europa"] },
	{ code: "CL", name: "Chile", continents: ["América"] },
	{ code: "CN", name: "China", continents: ["Ásia"] },
	{ code: "CY", name: "Chipre", continents: ["Europa"] },
	{ code: "CC", name: "Cocos, Ilhas", continents: ["Oceania"] },
	{ code: "CO", name: "Colômbia", continents: ["América"] },
	{ code: "KM", name: "Comores", continents: ["África"] },
	{ code: "CG", name: "República do Congo", continents: ["África"] },
	{ code: "CD", name: "República Democrática do Congo", continents: ["África"] },
	{ code: "CK", name: "Cook, Ilhas", continents: ["Oceania"] },
	{ code: "KR", name: "Coreia do Sul", continents: ["Ásia"] },
	{ code: "KP", name: "Coreia do Norte", continents: ["Ásia"] },
	{ code: "CI", name: "Costa do Marfim", continents: ["África"] },
	{ code: "CR", name: "Costa Rica", continents: ["América"] },
	{ code: "HR", name: "Croácia", continents: ["Europa"] },
	{ code: "CU", name: "Cuba", continents: ["América"] },
	{ code: "CW", name: "Curaçau", continents: ["América"] },
	{ code: "DK", name: "Dinamarca", continents: ["Europa"] },
	{ code: "DJ", name: "Djibuti", continents: ["África"] },
	{ code: "DM", name: "Dominica", continents: ["América"] },
	{ code: "DO", name: "República Dominicana", continents: ["América"] },
	{ code: "EG", name: "Egito", continents: ["África", "Ásia"] },
	{ code: "SV", name: "El Salvador", continents: ["América"] },
	{ code: "AE", name: "Emirados Árabes Unidos", continents: ["Ásia"] },
	{ code: "EC", name: "Equador", continents: ["América"] },
	{ code: "ER", name: "Eritreia", continents: ["África"] },
	{ code: "SK", name: "Eslováquia", continents: ["Europa"] },
	{ code: "SI", name: "Eslovênia", continents: ["Europa"] },
	{ code: "ES", name: "Espanha", continents: ["Europa"] },
	{ code: "US", name: "Estados Unidos", continents: ["América"] },
	{ code: "EE", name: "Estónia", continents: ["Europa"] },
	{ code: "SZ", name: "Essuatíni", continents: ["África"] },
	{ code: "SJ", name: "Esvalbarde e Jan Mayen", continents: ["Europa"] },
	{ code: "ET", name: "Etiópia", continents: ["África"] },
	{ code: "FO", name: "Feroé, Ilhas", continents: ["Europa"] },
	{ code: "FJ", name: "Fiji", continents: ["Oceania"] },
	{ code: "PH", name: "Filipinas", continents: ["Ásia"] },
	{ code: "FI", name: "Finlândia", continents: ["Europa"] },
	{ code: "FR", name: "França", continents: ["Europa"] },
	{ code: "GA", name: "Gabão", continents: ["África"] },
	{ code: "GM", name: "Gâmbia", continents: ["África"] },
	{ code: "GH", name: "Gana", continents: ["África"] },
	{ code: "GE", name: "Geórgia", continents: ["Ásia"] },
	{ code: "GS", name: "Ilhas Geórgia do Sul e Sanduíche do Sul", continents: ["Indefinido"] },
	{ code: "GI", name: "Gibraltar", continents: ["Europa"] },
	{ code: "GD", name: "Granada", continents: ["América"] },
	{ code: "GR", name: "Grécia", continents: ["Europa"] },
	{ code: "GL", name: "Groenlândia", continents: ["América"] },
	{ code: "GP", name: "Guadalupe", continents: ["América"] },
	{ code: "GU", name: "Guam", continents: ["Oceania"] },
	{ code: "GT", name: "Guatemala", continents: ["América"] },
	{ code: "GG", name: "Guernsey", continents: ["Europa"] },
	{ code: "GY", name: "Guiana", continents: ["América"] },
	{ code: "GF", name: "Guiana Francesa", continents: ["América"] },
	{ code: "GW", name: "Guiné-Bissau", continents: ["África"] },
	{ code: "GN", name: "Guiné-Conacri", continents: ["África"] },
	{ code: "GQ", name: "Guiné Equatorial", continents: ["África"] },
	{ code: "HT", name: "Haiti", continents: ["América"] },
	{ code: "HM", name: "Ilha Heard e Ilhas McDonald", continents: ["Indefinido"] },
	{ code: "HN", name: "Honduras", continents: ["América"] },
	{ code: "HK", name: "Hong Kong", continents: ["Ásia"] },
	{ code: "HU", name: "Hungria", continents: ["Europa"] },
	{ code: "YE", name: "Iémen", continents: ["Ásia"] },
	{ code: "IN", name: "Índia", continents: ["Ásia"] },
	{ code: "ID", name: "Indonésia", continents: ["Ásia", "Oceania"] },
	{ code: "IQ", name: "Iraque", continents: ["Ásia"] },
	{ code: "IR", name: "Irã", continents: ["Ásia"] },
	{ code: "IE", name: "Irlanda", continents: ["Europa"] },
	{ code: "IS", name: "Islândia", continents: ["Europa"] },
	{ code: "IL", name: "Israel", continents: ["Ásia"] },
	{ code: "IT", name: "Itália", continents: ["Europa"] },
	{ code: "JM", name: "Jamaica", continents: ["América"] },
	{ code: "JP", name: "Japão", continents: ["Ásia"] },
	{ code: "JE", name: "Jersey", continents: ["Europa"] },
	{ code: "JO", name: "Jordânia", continents: ["Ásia"] },
	{ code: "KW", name: "Kuwait", continents: ["Ásia"] },
	{ code: "LA", name: "Laos", continents: ["Ásia"] },
	{ code: "LS", name: "Lesoto", continents: ["África"] },
	{ code: "LV", name: "Letônia", continents: ["Europa"] },
	{ code: "LB", name: "Líbano", continents: ["Ásia"] },
	{ code: "LR", name: "Libéria", continents: ["África"] },
	{ code: "LY", name: "Líbia", continents: ["África"] },
	{ code: "LI", name: "Listenstaine", continents: ["Europa"] },
	{ code: "LT", name: "Lituânia", continents: ["Europa"] },
	{ code: "LU", name: "Luxemburgo", continents: ["Europa"] },
	{ code: "MO", name: "Macau", continents: ["Ásia"] },
	{ code: "MK", name: "Macedônia do Norte", continents: ["Europa"] },
	{ code: "MG", name: "Madagáscar", continents: ["África"] },
	{ code: "YT", name: "Maiote", continents: ["África"] },
	{ code: "MY", name: "Malásia", continents: ["Ásia"] },
	{ code: "MW", name: "Maláui", continents: ["África"] },
	{ code: "MV", name: "Maldivas", continents: ["Ásia"] },
	{ code: "ML", name: "Mali", continents: ["África"] },
	{ code: "MT", name: "Malta", continents: ["Europa"] },
	{ code: "FK", name: "Ilhas Malvinas (Falkland)", continents: ["América"] },
	{ code: "IM", name: "Man, Ilha de", continents: ["Europa"] },
	{ code: "MP", name: "Marianas Setentrionais", continents: ["Oceania"] },
	{ code: "MA", name: "Marrocos", continents: ["África"] },
	{ code: "MH", name: "Marshall, Ilhas", continents: ["Oceania"] },
	{ code: "MQ", name: "Martinica", continents: ["América"] },
	{ code: "MU", name: "Maurícia", continents: ["África"] },
	{ code: "MR", name: "Mauritânia", continents: ["África"] },
	{ code: "UM", name: "Ilhas Menores Distantes dos Estados Unidos", continents: ["América"] },
	{ code: "MX", name: "México", continents: ["América"] },
	{ code: "MM", name: "Mianmar", continents: ["Ásia"] },
	{ code: "FM", name: "Micronésia, Estados Federados da", continents: ["Oceania"] },
	{ code: "MZ", name: "Moçambique", continents: ["África"] },
	{ code: "MD", name: "Moldávia", continents: ["Europa"] },
	{ code: "MC", name: "Mônaco", continents: ["Europa"] },
	{ code: "MN", name: "Mongólia", continents: ["Ásia"] },
	{ code: "MS", name: "Monserrate", continents: ["América"] },
	{ code: "ME", name: "Montenegro", continents: ["Europa"] },
	{ code: "NA", name: "Namíbia", continents: ["África"] },
	{ code: "CX", name: "Natal, Ilha do (Ilha Christmas)", continents: ["Oceania"] },
	{ code: "NR", name: "Nauru", continents: ["Oceania"] },
	{ code: "NP", name: "Nepal", continents: ["Ásia"] },
	{ code: "NI", name: "Nicarágua", continents: ["América"] },
	{ code: "NE", name: "Níger", continents: ["África"] },
	{ code: "NG", name: "Nigéria", continents: ["África"] },
	{ code: "NU", name: "Niue", continents: ["Oceania"] },
	{ code: "NF", name: "Norfolque, Ilha", continents: ["Oceania"] },
	{ code: "NO", name: "Noruega", continents: ["Europa"] },
	{ code: "NC", name: "Nova Caledônia", continents: ["Oceania"] },
	{ code: "NZ", name: "Nova Zelândia (Aotearoa)", continents: ["Oceania"] },
	{ code: "OM", name: "Omã", continents: ["Ásia"] },
	{ code: "NL", name: "Países Baixos (Holanda)", continents: ["Europa"] },
	{ code: "PW", name: "Palau", continents: ["Oceania"] },
	{ code: "PS", name: "Palestina", continents: ["Ásia"] },
	{ code: "PA", name: "Panamá", continents: ["América"] },
	{ code: "PG", name: "Papua-Nova Guiné", continents: ["Oceania"] },
	{ code: "PK", name: "Paquistão", continents: ["Ásia"] },
	{ code: "PY", name: "Paraguai", continents: ["América"] },
	{ code: "PE", name: "Peru", continents: ["América"] },
	{ code: "PN", name: "Pitcairn", continents: ["Oceania"] },
	{ code: "PF", name: "Polinésia Francesa", continents: ["Oceania"] },
	{ code: "PL", name: "Polônia", continents: ["Europa"] },
	{ code: "PR", name: "Porto Rico", continents: ["América"] },
	{ code: "PT", name: "Portugal", continents: ["Europa"] },
	{ code: "KE", name: "Quênia", continents: ["África"] },
	{ code: "KG", name: "Quirguistão", continents: ["Ásia"] },
	{ code: "KI", name: "Quiribáti", continents: ["Oceania"] },
	{ code: "GB", name: "Reino Unido da Grã-Bretanha e Irlanda do Norte", continents: ["Europa"] },
	{ code: "RE", name: "Reunião", continents: ["África"] },
	{ code: "RO", name: "Romênia", continents: ["Europa"] },
	{ code: "RW", name: "Ruanda", continents: ["África"] },
	{ code: "RU", name: "Rússia", continents: ["Europa", "Ásia"] },
	{ code: "EH", name: "Saara Ocidental", continents: ["África"] },
	{ code: "AS", name: "Samoa Americana", continents: ["Oceania"] },
	{ code: "WS", name: "Samoa (Samoa Ocidental)", continents: ["Oceania"] },
	{ code: "SB", name: "Salomão, Ilhas", continents: ["Oceania"] },
	{ code: "SM", name: "San Marino", continents: ["Europa"] },
	{ code: "SH", name: "Santa Helena", continents: ["África"] },
	{ code: "LC", name: "Santa Lúcia", continents: ["América"] },
	{ code: "BL", name: "São Bartolomeu", continents: ["América"] },
	{ code: "KN", name: "São Cristóvão e Neves", continents: ["América"] },
	{ code: "MF", name: "São Martinho (França)", continents: ["América"] },
	{ code: "SX", name: "São Martinho (Países Baixos)", continents: ["América"] },
	{ code: "PM", name: "São Pedro e Miquelão", continents: ["América"] },
	{ code: "ST", name: "São Tomé e Príncipe", continents: ["África"] },
	{ code: "VC", name: "São Vicente e Granadinas", continents: ["América"] },
	{ code: "SC", name: "Seicheles", continents: ["África"] },
	{ code: "SN", name: "Senegal", continents: ["África"] },
	{ code: "LK", name: "Sri Lanka", continents: ["Ásia"] },
	{ code: "SL", name: "Serra Leoa", continents: ["África"] },
	{ code: "RS", name: "Sérvia", continents: ["Europa"] },
	{ code: "SG", name: "Singapura", continents: ["Ásia"] },
	{ code: "SY", name: "Síria", continents: ["Ásia"] },
	{ code: "SO", name: "Somália", continents: ["África"] },
	{ code: "SD", name: "Sudão", continents: ["África"] },
	{ code: "SS", name: "Sudão do Sul", continents: ["África"] },
	{ code: "SE", name: "Suécia", continents: ["Europa"] },
	{ code: "CH", name: "Suíça", continents: ["Europa"] },
	{ code: "SR", name: "Suriname", continents: ["América"] },
	{ code: "TH", name: "Tailândia", continents: ["Ásia"] },
	{ code: "TW", name: "Taiwan", continents: ["Ásia"] },
	{ code: "TJ", name: "Tajiquistão", continents: ["Ásia"] },
	{ code: "TZ", name: "Tanzânia", continents: ["África"] },
	{ code: "TF", name: "Terras Austrais e Antárticas Francesas", continents: ["Indefinido"] },
	{ code: "IO", name: "Território Britânico do Oceano Índico", continents: ["África"] },
	{ code: "TL", name: "Timor-Leste", continents: ["Ásia"] },
	{ code: "TG", name: "Togo", continents: ["África"] },
	{ code: "TO", name: "Tonga", continents: ["Oceania"] },
	{ code: "TK", name: "Toquelau", continents: ["Oceania"] },
	{ code: "TT", name: "Trindade e Tobago", continents: ["América"] },
	{ code: "TN", name: "Tunísia", continents: ["África"] },
	{ code: "TC", name: "Turcas e Caicos", continents: ["América"] },
	{ code: "TM", name: "Turcomenistão", continents: ["Ásia"] },
	{ code: "TR", name: "Turquia", continents: ["Ásia", "Europa"] },
	{ code: "TV", name: "Tuvalu", continents: ["Oceania"] },
	{ code: "UA", name: "Ucrânia", continents: ["Europa"] },
	{ code: "UG", name: "Uganda", continents: ["África"] },
	{ code: "UY", name: "Uruguai", continents: ["América"] },
	{ code: "UZ", name: "Usbequistão", continents: ["Ásia"] },
	{ code: "VU", name: "Vanuatu", continents: ["Oceania"] },
	{ code: "VA", name: "Vaticano", continents: ["Europa"] },
	{ code: "VE", name: "Venezuela", continents: ["América"] },
	{ code: "VN", name: "Vietnã", continents: ["Ásia"] },
	{ code: "VI", name: "Ilhas Virgens Americanas", continents: ["América"] },
	{ code: "VG", name: "Ilhas Virgens Britânicas", continents: ["América"] },
	{ code: "WF", name: "Wallis e Futuna", continents: ["Oceania"] },
	{ code: "ZM", name: "Zâmbia", continents: ["África"] },
	{ code: "ZW", name: "Zimbábue", continents: ["África"] },
	{ code: "XK", name: "Kosovo", continents: ["Europa"] },
	{ code: "GB-ENG", name: "Inglaterra", continents: ["Europa"] },
	{ code: "GB-NIR", name: "Irlanda do Norte", continents: ["Europa"] },
	{ code: "GB-SCT", name: "Escócia", continents: ["Europa"] },
	{ code: "GB-WLS", name: "País de Gales", continents: ["Europa"] }
]
